### PR TITLE
RFC: Add Procfile as stand-alone buildpack to Tiny builder

### PR DESCRIPTION
**Pull request by ForestEckhardt**
[Readable](https://github.com/paketo-buildpacks/tiny-builder/blob/add-procfile/rfcs/0001-add-procfile.md)

### CODE REVIEW

**Comment by fg-j** [comment]
It looks like the Procfile buildpack [sets the Procfile process up as a direct process](https://github.com/paketo-buildpacks/procfile/blob/a36fb09721cd8fa05215333379e406e20391612f/procfile/build.go#L48) if it's being run on the Tiny stack. I tried using our [Procfile sample](https://github.com/paketo-buildpacks/samples/tree/main/procfile). The build succeeds:
```
pack build procfile-tiny --builder paketobuildpacks/builder:tiny --buildpack gcr.io/paketo-buildpacks/procfile
```

But running the container fails with:
```
docker run --tty --publish 8080:8080 procfile-tiny
ERROR: failed to launch: path lookup: exec: "FOLDER=web": executable file not found in $PATH
```

It seems that the format of a valid Procfile is different on the Tiny stack. I'd like to see an example laid out in this RFC of a valid Procfile for the tiny stack. And I think documenting this subtlety and/or adding a sample should be part of implementing the RFC.

**Comment by ForestEckhardt** [comment]
@fg-j The following [PR](https://github.com/paketo-buildpacks/samples/pull/84) has an updated version of the Procfile sample app that is compatible to run on Tiny.

**Review by fg-j — APPROVED** [review]
Looks good to me. Need another approving review from @ekcasey or @dumez-k to accept this RFC.

**Comment by fg-j** [comment]
We should probably also relocate this to https://github.com/paketo-buildpacks/builder since that's where other builder RFCs live.

**Review by ekcasey — APPROVED** [review]

**Comment by ForestEckhardt** [comment]
The [RFC](https://github.com/paketo-buildpacks/builder/pull/49) has been opened in the builder repo. Closing this PR in favor of the one in the top level builder repo.

**Pull request closed without merging**
